spring:
  application:
    name: security-security

  # R2DBC конфигурация (реактивное подключение)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/mydatabase?ssl=false
    username: postgres
    password: ${DB_PASS}

  # JDBC конфигурация (для Liquibase)
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/mydatabase?ssl=false
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  # Настройки Liquibase
  liquibase:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/mydatabase?ssl=false
    user: postgres
    password: ${DB_PASS}

  # JPA/Hibernate настройки
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # WebFlux настройки
  webflux:
    http2:
      enabled: true
  codec:
    max-in-memory-size: 16MB
  main:
    web-application-type: reactive

  # Actuator настройки
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      tags:
        application: ${spring.application.name}
      enable:
        system:
          cpu: false

# Настройки логирования
logging:
  level:
    reactor.netty: debug
    org.springframework.web.reactive: debug
# Security настройки
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
